services:
  - type: web
    name: esign-api
    runtime: node
    plan: free
    buildCommand: bash render-build.sh
    preDeployCommand: pnpm --filter @esign/db migrate:deploy
    startCommand: pnpm --filter @esign/api start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_VERSION
        value: 22.22.2
      - key: NODE_OPTIONS
        value: "--max-old-space-size=320"
      - key: DATABASE_URL
        fromDatabase:
          name: esign-postgres
          property: connectionString
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: AES_ENCRYPTION_KEY
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_KMS_KEY_ID
        sync: false
      - key: FORCE_LOCAL_STORAGE
        value: "false"
      - key: REDIS_URL
        fromService:
          name: esign-redis
          type: redis
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://esign-web.onrender.com
      - key: API_URL
        value: https://esign-api.onrender.com
      - key: TOTP_APP_NAME
        value: ESign
      - key: TOTP_ISSUER
        value: ESign
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: X402_CHAIN_ID
        value: "84532"
      - key: X402_RPC_URL
        value: https://sepolia.base.org
      - key: X402_FACILITATOR_URL
        value: https://facilitator.coinbase.com
      - key: X402_PRICE_PER_SIGN
        value: "0.000091"
      - key: X402_WALLET_ADDRESS
        sync: false

  - type: web
    name: esign-web
    runtime: node
    plan: free
    buildCommand: bash render-web-build.sh
    startCommand: pnpm --filter @esign/web start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_API_URL
        value: https://esign-api.onrender.com
      - key: NEXTAUTH_URL
        value: https://esign-web.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXT_PUBLIC_X402_PRICE_PER_SIGN
        value: "0.000091"
      - key: NEXT_PUBLIC_X402_WALLET
        sync: false

  - type: redis
    name: esign-redis
    plan: free

databases:
  - name: esign-postgres
    plan: free
